### ISSUE TITLE
Reduce size of docker images

### ISSUE THREAD

**Issue by cjgrady** [specifysystems/lmpy#194]
So far, I have not taken any steps to reduce the size of the docker images that are created for lmpy.  Ben and Max have suggested a multi-stage build where the first image installs packages with Conda and a second image uses the alpine base image and just copies over the installed libraries.

https://docs.docker.com/develop/develop-images/multistage-build/ may have some helpful tips for doing this.

**Comment by zzeppozz** [comment]
Consider AWS deployment instead
