### ISSUE TITLE
Add glossary of terms for lmpy to sphinx documentation

### ISSUE THREAD

**Issue by cjgrady** [specifysystems/lmpy#222]
It would be useful to have a glossary of lmpy terms that are probably not common knowledge (like data wranglers).  Link these terms where appropriate throughout the documentation.

Sphinx has glossary functionality that we can use, more information can be found at: https://sublime-and-sphinx-guide.readthedocs.io/en/latest/glossary.html

**Comment by cjgrady** [comment]
I have added a glossary page at: [glossary.rst](https://github.com/specifysystems/lmpy/blob/main/_sphinx_config/pages/glossary.rst) with a couple of entries but we need to add a few more terms to it.

**Comment by zzeppozz** [comment]
Documentation in https://github.com/biotaphy/tutorials
