### ISSUE TITLE
Create a common entrypoint script for all lmpy tools

### ISSUE THREAD

**Issue by cjgrady** [specifysystems/lmpy#275]
**Is your feature request related to a problem? Please describe.**

It seems that it is encouraged to have a common entry point for docker containers, even in single shot mode.  We could expose all of the lmpy tools by creating a top level tool that exposed the other tools via sub-commands.

**Describe the solution you'd like**
I think we could use: https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_subparsers to enable this.

**Comment by zzeppozz** [comment]
Entrypoint creates a docker image, script and documentation in https://github.com/biotaphy/tutorials
