### ISSUE TITLE
Find and correct copy / paste errors and typos and minor code fixes

### ISSUE THREAD

**Issue by cjgrady** [specifysystems/lmpy#322]
## Describe the bug

There are some copy / paste errors and typos that were generated when new scripts were created that are very similar to others (ex. wrangle_species_list, wrangle_matrix, etc.).  @zzeppozz has seen a few of these errors and there are others to be found.  Carefully look through the code and fix as many of these as possible before releasing version 3.2.

There are a few of other things that can be improved found by lgtm (https://lgtm.com/projects/g/specifysystems/lmpy/?mode=list).

Clean things up as much as possible for version 3.2.

Note any problems encountered here.

To fix:
 - [ ] Issues at https://lgtm.com/projects/g/specifysystems/lmpy/?mode=list
 - [x] lmpy.tools.wrangle_species_list -> program name is wrong (wrangle_matrix)
 - [x] Fix double file extension for generated temporary files
 - [ ] Document using the data wrangler factory with module specifications

**Comment by cjgrady** [comment]
Double file extension and wrangle_species_list program were fixed in https://github.com/specifysystems/lmpy/pull/324/commits/f4223d8dda9f96f9cdf34824a7295b67d62e98f7

**Comment by zzeppozz** [comment]
Tons of untested code fixed
