### ISSUE TITLE
Document how to use wrangle_matrix tool for tutorial

### ISSUE THREAD

**Issue by cjgrady** [specifysystems/lmpy#332]
Document how to wrangle matrices using the wrangle_matrix tool and from a python script. 

- [ ] Document how to use `wrangle_matrix` in sphinx docs
- [ ] Document how to wrangle matrices using a python script in sphinx docs
- [ ] Add pytest tests that replicate the instructions in the wrangle matrix sphinx docs

**Comment by zzeppozz** [comment]
Documentation in https://github.com/biotaphy/tutorials
